baseURL: "https://tagsdev.click/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: tagsdev
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: ":en:"
        languageAltTitle: English
        weight: 2
        title: TagsDev
        profileMode:
            enabled: true
            title: Mark Taguiad
            imageUrl: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f317.svg"
            imageTitle: ProfileMode image
            # imageWidth: 120
            # imageHeight: 120
            subtitle: "devops | philomath"
            #buttons:
            #    - name: Blog
            #      url: posts
            #    - name: Profile Mode
            #      url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
        menu:
            main:
                - name: Blog
                  url: posts/
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: Tags/
                  weight: 10
                - name: Luna
                  url: "https://www.imcollectingmoonlight.com/"

    

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Tagsdev | Devops"
    author: Mark Taguiad
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: Tagsdev
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Tagsdev"
        Content: >
            Welcome to demo of hugo's theme PaperMod.
            - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.
            - Do give a 🌟 on Github !
            - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).
    socialIcons:
        - name: github
          url: "https://github.com/mcbtaguiad/"
        - name: Spotify
          url: "https://open.spotify.com/playlist/0D1gr5jrtvcM0K6c40hAzO?si=079b83f114dd4360"
        - name: Rss
          url: "index.xml"
        - name: Linkedin
          url: "https://www.linkedin.com/in/mark-christian-taguiad/"


    editPost:
        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true