---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  #namespace: web-tagsdev-hugo-prod
  name: tagsdev-hugo-ingress
  annotations:
    #acme.cert-manager.io/http01-edit-in-place: "true"
    #cert-manager.io/issuer: "letsencrypt-prod"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #acme.cert-manager.io/dns01-edit-in-place: "true"
    kubernetes.io/ingress.class: "nginx"

spec:
  tls:
  - hosts:
      - tagsdev.click
    secretName: tagsdev-hugo-tls
  rules:
  - host: tagsdev.click
    http:
      paths:
      - path: /
        #pathType: ImplementationSpecific
        pathType: Prefix
        backend:
          service: 
            name: web
            port:
              number: 8080



---

