apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-tagsdev
  name: web-tagsdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-tagsdev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-tagsdev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - 'amd64'
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - 'worker'
          - weight: 10
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - 'true'
          - weight: 5
            preference:
              matchExpressions:
              - key: corecount
                operator: In
                values:
                - '2'
          - weight: 5
            preference:
              matchExpressions:
              - key: disk
                operator: In
                values:
                - 'hdd'
      containers:
        - image: mcbtaguiad/web-tagsdev-hugo:v1.0.1
          imagePullPolicy: Always
          name: web-tagsdev
          ports:
            - containerPort: 8080
      restartPolicy: Always
